1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -2,8 +2,23 @@
 # This script installs the Nginx web server and configures the initial "Hello
 # world" page.
 
-apt-get update -y
-apt-get install nginx -y
-sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
-/etc/init.d/nginx reload
-echo "Hello World!" > /usr/share/nginx/html/index.html
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: You need to be root to run this script" 1>&2
+  exit 1
+fi
+
+# Update the package list and install Nginx
+apt-get update
+apt-get install -y nginx
+
+# Create the default "Hello world" page
+echo "Hello World!" > /var/www/html/index.html
+
+# Start the Nginx service
+service nginx start
+
+if [[ ! $? ]]; then
+  echo "ERROR: Failed to start Nginx" 1>&2
+  exit 1
+fi
+
