1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -2,23 +2,28 @@
 # This script installs the Nginx web server and configures the initial "Hello
 # world" page.
 
-if [[ $EUID -ne 0 ]]; then
-  echo "ERROR: You need to be root to run this script" 1>&2
-  exit 1
-fi
-
-# Update the package list and install Nginx
+# Update package lists
 apt-get update
+
+# Install nginx
 apt-get install -y nginx
 
-# Create the default "Hello world" page
-echo "Hello World!" > /var/www/html/index.html
-
-# Start the Nginx service
-service nginx start
-
-if [[ ! $? ]]; then
-  echo "ERROR: Failed to start Nginx" 1>&2
-  exit 1
+# Check if nginx is installed successfully
+if [ $? -ne 0 ]; then
+	echo "Failed to install nginx. Exiting."
+	exit 1
 fi
 
+# Set nginx to listen on port 80
+sed -i 's/\(listen\s*\)80/\180/' /etc/nginx/sites-available/default
+
+# Restart nginx
+service nginx restart
+
+# Check if nginx is running
+if ! pgrep -x "nginx" > /dev/null; then
+	echo "Nginx failed to start. Exiting."
+	exit 1
+fi
+
+echo "Hello World" > /var/www/html/index.html
